---
title: "ORBIT for *E. coli*" 
subtitle: "Kilobase-scale oligonucleotide recombineering at high throughput and high efficiency"
output: 
  html_document:
    theme: cosmo
    toc: true
    toc_float: true
    self_contained: false
---

<br>

<center>

*This is a paper website for our manuscript. It is a convenient wrapper for the github code repo, which contains html versions of all code notebooks. Our goal is to help others use ORBIT, so we also link to several resources that may be of interest. We welcome any feedback - Thank you!*

*-Scott Saunders, Distinguished Fellow, UTSW Medical Center*

[bioRxiv preprint](https://www.biorxiv.org/content/10.1101/2023.06.28.546561v1)   \|   [github repository](github.com/saunders-lab/ecoli_orbit)   \| [Saunders lab ORBIT help page](https://saunderslab.org/research/ec_orbit/)   \|   [Targeting oligo design app](https://saunders-lab.shinyapps.io/ORBIT_TO_design_ecMG1655/)

</center>

# Abstract

------------------------------------------------------------------------

Microbiology and synthetic biology depend on reverse genetic approaches to manipulate bacterial genomes; however, existing methods require molecular biology to generate genomic homology, suffer from low efficiency, and are not easily scaled to high throughput applications. To overcome these limitations, we developed a system for creating kilobase-scale genomic modifications that uses DNA oligonucleotides to direct the integration of a non-replicating plasmid. This method, **O**ligonucleotide **R**ecombineering followed by **B**xb-1 **I**ntegrase **T**argeting (**ORBIT**) was pioneered in *Mycobacteria*, and here we adapt and expand it for *E. coli*. Our redesigned plasmid toolkit achieved nearly 1000x higher efficiency than λ Red recombination and enabled precise, stable knockouts (\<134 kb) and integrations (\<11 kb) of various sizes. Additionally, we constructed multi-mutants (double and triple) in a single transformation, using orthogonal attachment sites. At high throughput, we used pools of targeting oligonucleotides to knock out nearly all known transcription factor and small RNA genes, yielding accurate, genome-wide, single mutant libraries. By counting genomic barcodes, we also show ORBIT libraries can scale to thousands of unique members (\>30k). This work demonstrates that ORBIT for *E. coli* is a flexible reverse genetic system that facilitates rapid construction of complex strains and readily scales to create sophisticated mutant libraries.

<br>

# Code notebooks

------------------------------------------------------------------------

## Main figures

-   Figure 1. ORBIT overview and proof of principle. (No computational content)

-   [Figure 2. ORBIT protocol optimization.](https://saunders-lab.github.io/ecoli_orbit/code/main_figs/fig_2_protocol_optimization.html)

-   [Figure 3. Benchmarking ORBIT.](https://saunders-lab.github.io/ecoli_orbit/code/main_figs/fig_3_gold_stds.html)

-   [Figure 4. Large deletions and insertions with ORBIT.](https://saunders-lab.github.io/ecoli_orbit/code/main_figs/fig_4_sizes.html)

-   [Figure 5. Orthogonal double mutants.](https://saunders-lab.github.io/ecoli_orbit/code/main_figs/fig_5_multi_orbit.html)

-   Figure 6. Markerless and scarless ORBIT strategies. (No computational content)

-   [Figure 7. Barcoded and multi-locus mutant libraries.](https://saunders-lab.github.io/ecoli_orbit/code/main_figs/fig_7_BC_oPool.html)

-   [Figure 8. High throughput knockout libraries for transcription factor and small RNA genes.](TBD) link TBD

## Supplemental figures

-   Figure S1. Target oligo design principles and web app. (No computational content)

-   [Figure S2. Commercial oligo parameters and pricing.](https://saunders-lab.github.io/ecoli_orbit/code/supp_figs/supplement_protocol_optimization.html)

-   Figure S3. Troubleshooting attB only colonies. (No computational content)

-   Figure S4. Single gene deletion accuracy and stability. (No computational content)

-   [Figure S5. Helper plasmid efficiency and off target SNP mutation rate.](https://saunders-lab.github.io/ecoli_orbit/code/supp_figs/supp_mutation_rate.html)

-   Figure S6. Variable deletion size phenotypic accuracy. (No computational content)

-   Figure S7. Sanger sequence confirmation of *galK* deletions of various sizes. (No computational content)

-   Figure S8. Sanger sequence confirmation of *hisA, metA* and *leuD* deletions of various sizes. (No computational content)

-   Figure S9. Phenotypic accuracy of orthogonal and untargeted double mutants. (No computational content)

-   [Figure S10. Orthogonal att sites and triple mutant construction.]

-   [Figure S11. oPool library - Upstream and downstream reads for target loci.](https://saunders-lab.github.io/ecoli_orbit/code/supp_figs/mut_lib_grids.html)

-   Figure S12. Low abundance (Twist Biosciences) targeting oligo library processing. (No computational content)

-   [Figure S13. Short transcription factor library - Upstream and downstream reads for target loci.](https://saunders-lab.github.io/ecoli_orbit/code/supp_figs/mut_lib_grids.html)

-   [Figure S14. Long transcription factor deletion library - Upstream and downstream reads for target loci.](https://saunders-lab.github.io/ecoli_orbit/code/supp_figs/mut_lib_grids.html)

-   [Figure S15. Small RNA deletion library - Upstream and downstream reads for target loci.](https://saunders-lab.github.io/ecoli_orbit/code/supp_figs/mut_lib_grids.html)

-   [Figure S16. Explaining mutant library abundances.](https://saunders-lab.github.io/ecoli_orbit/code/supp_figs/supp_twist_lib.html)

-   [Figure S17. Correlations of oligo parameters and observed reads per target (perfect reads).](https://saunders-lab.github.io/ecoli_orbit/code/supp_figs/supp_twist_lib.html)

## Sequencing data

### galK BC

-   [galK random genomic barcodes - sequencing data analysis.](https://saunders-lab.github.io/ecoli_orbit/code/seq_data_processing/galK_BC_16N/galK_BC_16N_processing_analysis.html)

### Twist oligo design

-   [Twist oligo pool design - Transcription factors](https://saunders-lab.github.io/ecoli_orbit/code/twist_oligo_design/twist_orbit_TF_deletion.html)

-   [Twist oligo pool design - Small RNAs](https://saunders-lab.github.io/ecoli_orbit/code/twist_oligo_design/twist_orbit_small_RNA_deletion.html)

-   [Twist oligo pool design - Primers and cloning scheme](https://saunders-lab.github.io/ecoli_orbit/code/twist_oligo_design/twist_orbit_cloning_scheme.html)

### Mutant library characterization

-   [Mutant libraries - Junction #1 sequencing data processing.](https://saunders-lab.github.io/ecoli_orbit/code/seq_data_processing/left_side_TO_libs_processing.html)

-   [Mutant libraries - Junction #2 sequencing data processing.](https://saunders-lab.github.io/ecoli_orbit/code/seq_data_processing/right_side_TO_libs_processing.html)

-   [Mutant libraries - Junction #1 analysis.](https://saunders-lab.github.io/ecoli_orbit/code/seq_data_processing/left_side_TO_libs_analysis.html)

-   [Mutant libraries - Junction #2 analysis.](https://saunders-lab.github.io/ecoli_orbit/code/seq_data_processing/right_side_TO_libs_analysis.html)

-   [Mutant libraries - Combined junction 1 & 2 analysis.](https://saunders-lab.github.io/ecoli_orbit/code/seq_data_processing/upstream_downstream_combined_analysis.html)

### Twist TO abundance

-   [Twist TO abundance - Sequencing data processing.](https://saunders-lab.github.io/ecoli_orbit/code/seq_data_processing/TO_abundance/TO_abundance_processing.html)

-   [Twist TO abundance - Analysis.](https://saunders-lab.github.io/ecoli_orbit/code/seq_data_processing/TO_abundance/TO_abundance_analysis.html)

<br>

# Other resources

------------------------------------------------------------------------

## Protocols

-   [Saunders lab ORBIT protocols.](saunderslab.org/research/ec_orbit/protocols)

## DNA maps

-   [Plasmid maps](https://github.com/saunders-lab/ecoli_orbit/tree/main/data/DNA_maps/plasmids)

-   [Genomic loci](https://github.com/saunders-lab/ecoli_orbit/tree/main/data/DNA_maps/genomic_loci)

-   [Sequencing libraries](https://github.com/saunders-lab/ecoli_orbit/tree/main/data/DNA_maps/sequencing_libraries)

## Addgene plasmids

-   [Addgene page.](TBD) link TBD

## SRA raw sequencing data

-   [BioProject](https://www.ncbi.nlm.nih.gov/sra/PRJNA989253)

| Experiment                                 |   Library Name   |                             Run ID and Link                              |  Size  |
|--------------------------------|:-------------:|:----------------:|:----------:|
| galK barcodes                              |    galK_BC16N    | [SRR25076308](https://trace.ncbi.nlm.nih.gov/Traces/sra?run=SRR25076308) | 123 Mb |
| IDT oPool - left junction                  |     oPool_J1     | [SRR25076307](https://trace.ncbi.nlm.nih.gov/Traces/sra?run=SRR25076307) | 8.3 Mb |
| Twist short TF deletions - left junction   |   short_TF_J1    | [SRR25076303](https://trace.ncbi.nlm.nih.gov/Traces/sra?run=SRR25076303) | 25 Mb  |
| Twist long TF deletions - left junction    |    long_TF_J1    | [SRR25076301](https://trace.ncbi.nlm.nih.gov/Traces/sra?run=SRR25076301) | 16 Mb  |
| Twist small RNA deletions - left junction  |   small_RNA_J1   | [SRR25076299](https://trace.ncbi.nlm.nih.gov/Traces/sra?run=SRR25076299) | 18 Mb  |
| IDT oPool - right junction                 |     oPool_J2     | [SRR25076304](https://trace.ncbi.nlm.nih.gov/Traces/sra?run=SRR25076304) | 15 Mb  |
| Twist short TF deletions - right junction  |   short_TF_J2    | [SRR25076302](https://trace.ncbi.nlm.nih.gov/Traces/sra?run=SRR25076302) | 43 Mb  |
| Twist long TF deletions - right junction   |    long_TF_J2    | [SRR25076300](https://trace.ncbi.nlm.nih.gov/Traces/sra?run=SRR25076300) | 39 Mb  |
| Twist small RNA deletions - right junction |   small_RNA_J2   | [SRR25076298](https://trace.ncbi.nlm.nih.gov/Traces/sra?run=SRR25076298) | 30 Mb  |
| Twist short TF oligo abundance             | short_TF_oligos  | [SRR25076297](https://trace.ncbi.nlm.nih.gov/Traces/sra?run=SRR25076297) | 45 Mb  |
| Twist long TF oligo abundance              |  long_TF_oligos  | [SRR25076306](https://trace.ncbi.nlm.nih.gov/Traces/sra?run=SRR25076306) | 27 Mb  |
| Twist small RNA oligo abundance            | small_RNA_oligos | [SRR25076305](https://trace.ncbi.nlm.nih.gov/Traces/sra?run=SRR25076305) | 42 Mb  |

<br>
