---
title: "Figure S9: Orthogonal triple mutants"
subtitle: 'E. coli ORBIT 2022'
author: 'Scott H. Saunders'
output:
  html_document:
    theme: cosmo
    highlight: tango
    code_folding: show
    toc: yes
---


# Notes

This figure contains data from many different experiments that were used to optimize the protocol for ORBIT. 

----

Setup packages and plotting for the notebook:

```{r setup, echo=T, message=FALSE, warning=FALSE}
# Check packages
source("../tools/package_setup.R")
# Load packages
library(tidyverse)
library(cowplot)
library(kableExtra)
# Code display options
knitr::opts_chunk$set(tidy.opts=list(width.cutoff=60),tidy=FALSE, echo = TRUE, message=FALSE, warning=FALSE, fig.align="center", fig.retina = 2)
# Load plotting tools
source("../tools/plotting_tools.R")
#Modify the plot theme
theme_set(theme_notebook())
```

-----

# Fig. 5B - Full orthogonal heatmap

Read in the data.

```{r}


df_heatmap <- read_csv("../../data/low_throughput_experiments/2022_10_14_chlor_orth_2_data.csv") %>% mutate(eff = Chlor_count / LB_count)


df_heatmap
```

```{r}

plot_heatmap <- ggplot(df_heatmap, aes(x = attP, y = attB, fill = eff)) + 
  geom_tile(color = 'white', size = 0.25) + 
  geom_tile(data = . %>% filter(match == T), fill = NA, color = 'black', size = 0.5)+
  geom_text(aes(label = scales::label_percent(accuracy = 0.01)(eff)), size = 2.85)+
  scale_fill_viridis_c(trans = 'log',label = scales::percent_format(), breaks = c(0.005, 0.0005,0.00005)) + 
  labs(y = 'attB version\n(∆galK targeting oligo)' , x = 'attP version\n(pInt_chlorR)', fill = 'Efficiency')

plot_heatmap
```

```{r}
theme_set(theme_figure())


#fig_s9 <- plot_grid(plot_heatmap + guides(fill = 'none'), plot_eff, nrow = 1,
#                   align = 'hv', axis = 'lr', scale = 1,
#                   labels = c('B','C'))


#fig_5_multi

plot_heatmap

save_plot("../../figures/r_pdf_figs/supp_figs/fig_s9_full_orth_heatmap.pdf", plot_heatmap, base_width = 4, base_height = 3)
```

```{r}
sessionInfo()
```